/**
 * The error codes that this client generates itself, as opposed to those
 * returned by the web service.
 */
export type ClientErrorCode =
  | 'FETCH_ERROR'
  | 'HTTP_STATUS_CODE_ERROR'
  | 'INVALID_RESPONSE_BODY'
  | 'NETWORK_TIMEOUT'
  | 'SERVER_ERROR';

/**
 * The `code` exposed on a {@link WebServiceError}. This is one of the
 * client-generated {@link ClientErrorCode} values or any other string returned
 * by the web service. The `& {}` keeps the union open to arbitrary strings
 * while still offering autocompletion for the known client codes.
 */
export type WebServiceErrorCode = ClientErrorCode | (string & {});

export interface WebServiceClientError {
  /**
   * The error code returned by the web service or generated by this client.
   */
  code: WebServiceErrorCode;
  /**
   * A human-readable description of the error. This is an alias of the standard
   * `Error` `message`.
   */
  error: string;
  /**
   * The HTTP status code, when the error originated from an HTTP response.
   * Absent for network-level errors.
   */
  status?: number;
  /**
   * The URL that was being requested when the error occurred.
   */
  url: string;
  /**
   * The underlying error that caused this one, when available (for example,
   * the network error behind a `FETCH_ERROR`).
   */
  cause?: unknown;
}
