name: Lint
on:
  pull_request:
  push:
  schedule:
    - cron: '3 20 * * SUN'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install
      - run: npm run lint
      - run: npm run prettier:ci
